# Generated by Django 5.1.7 on 2025-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentexamsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamsubmission',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
