# Generated by Django 5.1.7 on 2025-04-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentexamsubmission_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamsubmission',
            name='snapshots',
            field=models.JSONField(default=list),
        ),
    ]
