# Generated by Django 5.1.7 on 2025-04-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentexamsubmission_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamsubmission',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
